// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzX4VaKu9_8fBjZo3_vTS8isJJF0D-9U',
    appId: '1:1037221437406:web:e48725144818615d05874f',
    messagingSenderId: '1037221437406',
    projectId: 'chatapp-5a14f',
    authDomain: 'chatapp-5a14f.firebaseapp.com',
    storageBucket: 'chatapp-5a14f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGby-MadFpiKg1gHn7kwfe4Jm343nquzI',
    appId: '1:1037221437406:android:aca83d602e74edaa05874f',
    messagingSenderId: '1037221437406',
    projectId: 'chatapp-5a14f',
    storageBucket: 'chatapp-5a14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEigFxIG54UgM1MPYUY4CyKLShNUx6_Ns',
    appId: '1:1037221437406:ios:bf66533c9740b8c805874f',
    messagingSenderId: '1037221437406',
    projectId: 'chatapp-5a14f',
    storageBucket: 'chatapp-5a14f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEigFxIG54UgM1MPYUY4CyKLShNUx6_Ns',
    appId: '1:1037221437406:ios:bf66533c9740b8c805874f',
    messagingSenderId: '1037221437406',
    projectId: 'chatapp-5a14f',
    storageBucket: 'chatapp-5a14f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQzX4VaKu9_8fBjZo3_vTS8isJJF0D-9U',
    appId: '1:1037221437406:web:98769bd3e25a488605874f',
    messagingSenderId: '1037221437406',
    projectId: 'chatapp-5a14f',
    authDomain: 'chatapp-5a14f.firebaseapp.com',
    storageBucket: 'chatapp-5a14f.appspot.com',
  );
}
